### PR TITLE
gui: update Chinese translation

### PR DESCRIPTION
**Pull request by cpuwolf**
zbmate_com_obs_addon02 2018-06-08

### CODE REVIEW

**Comment by sthalik** [comment]
Great! Are there problems with a right-to-left writing system?

**Comment by stylerope** [comment]
awsome!i

**Comment by cpuwolf** [comment]
@sthalik  no problem here.：P

**Comment by sthalik** [comment]
@cpuwolf can you check your email please?

**Comment by cpuwolf** [comment]
@sthalik I replied you weeks ago, but no reply. spam?

**Comment by sthalik** [comment]
@cpuwolf I haven't received it. Just in case, my email is <<sthalik@misaki.pl>>. Can you please resend?

**Comment by sthalik** [comment]
@cpuwolf just in case, it's the matter concerning the "trackmouse" project.

**Pull request merged**
