### PR TITLE
Add Tobii Eye Tracker input

### PR DESCRIPTION
**Pull request by khoanguyen-3fc**
Add Tobii Eye Tracker as input.

Tested with Tobii SDK 4.0 and Tobii Eye Tracker 4C.

### CODE REVIEW

**Comment by sthalik** [comment]
It appears that the SDK doesn't come with a 32-bit variety. It needs to be put into a subprocess using `compat/shm.h` and `QProcess`. You can see how it's done in `video/ps3eye`.

You can either do it by yourself or wait for me to have some spare time.

**Comment by khoanguyen-3fc** [comment]
Is it possible for us to consider downgrading the SDK to version 2.2, which is available on this link: https://www.nuget.org/packages/Tobii.StreamEngine.Native/ ?
 
image

**Comment by khoanguyen-3fc** [comment]
I need to perform some refactoring to ensure compatibility with SDK v2

**Comment by sthalik** [comment]
Please see if https://ananke.misaki.pl/opentrack/opentrack-test-20230926_01.7z works.

Also, do you want a commit bit?

**Comment by khoanguyen-3fc** [comment]
It is working as expected.

As for the commit bit, I'm afraid I won't have enough spare time to contribute regularly.

**Pull request merged**
