### PR TITLE
Easy Tracker v0.1

### PR DESCRIPTION
**Pull request by Slion**

### CODE REVIEW

**Comment by sthalik** [comment]
@Slion how are we doing on the tabs vs spaces front?

**Comment by sthalik** [comment]
As for the build failing, I'm gonna take care of it with some cmake-fu.

**Comment by Slion** [comment]
> how are we doing on the tabs vs spaces front?

Well it should be all space really. Spotted any issue?

**Comment by sthalik** [comment]
@Slion feel free to merge once you get rid of all excess duplicate code. Any other issues are secondary. Can you think of a better name though? :) How about "Light Tracker" or "LED tracker"? In any case I'd like having the name imply what kind of device is used for tracking. "Easy Tracker" is generic.

**Comment by Slion** [comment]
> feel free to merge

Thanks 😄 

>  once you get rid of all excess duplicate code

Still mostly settings and UI. Not worth creating a common library over it as they will eventually go their on way anyway.

> Can you think of a better name though? :) How about "Light Tracker" or "LED tracker"? In any case I'd like having the name imply what kind of device is used for tracking. "Easy Tracker" is generic.

Actually I did not want to make it device specific as it could evolve really. Therefore I thought I rather use a "brand" name for it.

**Comment by Slion** [comment]
It's starting to look really good. I'll be merging that soon.

**Comment by sthalik** [comment]
@Slion good! Can you think of a good name for it?

**Comment by Slion** [comment]
> Can you think of a good name for it?

Easy is as good a name as any.
See https://github.com/opentrack/opentrack/pull/932#issuecomment-484526281

**Comment by sthalik** [comment]
> Actually I did not want to make it device specific as it could evolve really. Therefore I thought I rather use a "brand" name for it.

The issue here is that a light blob tracker isn't generic as-is. See the amount of non-light-tracking trackers here.

I'll leave it to your discretion.

**Comment by Slion** [comment]
> The issue here is that a light blob tracker isn't generic as-is. See the amount of non-light-tracking trackers here.

I see what you mean.

> I'll leave it to your discretion.

Thanks, I'll leave it as it is for now. Re-branding could still be done later on if and when we judge it necessary.

**Comment by sthalik** [comment]
I'm curious, does Kalman help you much?

**Comment by Slion** [comment]
> I'm curious, does Kalman help you much?

I left it in, but I don't think it brings much if anything at all. Probably because I don't know how to use it.

**Comment by Slion** [comment]
It could also be that OpenCV Kalman Filter implementation is primarily intended to be used to predict positions when loosing signal rather than do any filtering. Though is theory if you can detect bad or noisy poses then you could use the predicted one from the KF instead. Interesting thought, I guess that's how it ought to be used.

**Comment by sthalik** [comment]
Note that Kalman prediction for filtering suffers from its own share of problems, e.g. overshoot, sluggish response. I'd advise against settings that trust the model more than the raw data. You're better off ignoring bad frames entirely.

**Pull request merged**
