### PR TITLE
x-plane plugin

### PR DESCRIPTION
**Pull request by miniskipper**
macro rename
support head roll movement in plugin

### CODE REVIEW

**Comment by sthalik** [comment]
Thank you

**Comment by sthalik** [comment]
Do you wish to maintain Linux support in opentrack?

**Comment by miniskipper** [comment]
Hi,
roll: when the tracking stops the roll stays at the last value. I found no easy possibility to control it with mouse/keyboard. Maybe it would be better to save the initial value instead of resetting to 0.

There is still some work to do:
- reinit view when plane is switched inflight (XPLM_MSG_PLANE_LOADED)
- dont move outside the plane
- add a possibility to save other views (passenger, copilot, ...)


Linux support: trying my best :)

**Comment by sthalik** [comment]
Hey,

It's best you handle it if you want to do the changes.

Please make the change to allocate WineSHM as `static` as to avoid dynamic memory allocation via `calloc(3)`. The `.bss` section is always preinitialized to zeros.

**Pull request merged**
