### PR TITLE
Linux/X11: Fix hotkeys

### PR DESCRIPTION
**Pull request by miniskipper**
See issue #577

### CODE REVIEW

**Comment by sthalik** [comment]
@miniskipper please see if https://github.com/opentrack/opentrack/commit/f8634b81548833969b79f2f0673298dffcadba32 is to your liking. I implemented hashing keycodes together with modifiers. It also doesn't seem to be necessary to block the key with numlock and scroll lock.

If this is to your liking, I'll put my own changes on top of merging yours.

**Comment by miniskipper** [comment]
@sthalik Sadly this does only work, if numlock on the keyboard is disabled. Thats why the key gets grabbed 4 times (num, scroll, both, none). Is it possible you are developing on a laptop? I wondered why hotkeys where working on my laptop - numlock is disabled there by default because of no dedicated numpad :)

**Comment by sthalik** [comment]
On my PC104 keyboard, the "Num" modifier only gets raised if it's a number pad key being pressed. For other keys its state doesn't matter. I need to actually boot the Linux, something is amiss here.

**Comment by sthalik** [comment]
@miniskipper we'd rather have a 1:1 mapping between keys with their modifiers, as recognized by Qt and X11. See how xev(1) reports KP_1 or KP_Home rather than the regular variants. It already exists for the Windows keyboard, see `logic/win32-shortcut.cpp`.

"Translating keysym to keycode" as it is right now is just a half-assed way that makes half the keys not work.

I don't have time to work on it soon but welcome contributions.

**Comment by miniskipper** [comment]
The X Server treads the num lock key (and others) as a separate modifier. I think thats "normal"
For example have a look at the grabKey function in https://raw.githubusercontent.com/xfce-mirror/xfwm4/master/src/keyboard.c
I have seen code like this in almost every application that uses hotkeys under X.

**Comment by sthalik** [comment]
:+1: :cat2:

**Pull request merged**
