### PR TITLE
proto-wine UI changes

### PR DESCRIPTION
**Pull request by Priton-CE**
see RFC https://github.com/opentrack/opentrack/issues/1618

### CODE REVIEW

**Comment by sthalik** [comment]
Can you rebase out changes outside `proto-wine`? Otherwise I'm going to squash and edit it on my own, and you might not agree with the result.

**Comment by Priton-CE** [comment]
I am going to create a new branch. And new PR as well unless you know of a way to change the branch in this PR.
Should I also remove the [change](https://github.com/Priton-CE/opentrack-StarCitizen/blob/054785d289f4e862b9df66d115e21ea5dce9daee/proto-wine/opentrack-wrapper-wine-windows.cxx#L69-L70) that forces an edit in the registry for both freetrack and NPClient?

**Comment by sthalik** [comment]
> Should I also remove the [change](https://github.com/Priton-CE/opentrack-StarCitizen/blob/054785d289f4e862b9df66d115e21ea5dce9daee/proto-wine/opentrack-wrapper-wine-windows.cxx#L69-L70) that forces an edit in the registry for both freetrack and NPClient?

Yes -- there are a few games that confuse themselves when both freetrack and npclient are present.

Apparently the PR branch can't be changed by anyone.

**Comment by Priton-CE** [comment]
https://github.com/opentrack/opentrack/pull/1620

**Pull request closed without merging**
