### PR TITLE
Add Eyeware Beam input

### PR DESCRIPTION
**Pull request by eyedav**
Eyeware Beam can be used as an input.

### CODE REVIEW

**Comment by sthalik** [comment]
Looks good other than the few minor things that I mentioned above.

**Review by sthalik — CHANGES_REQUESTED** [review]

**Comment by sthalik** [comment]
Merged, thanks! The test build is going to be ready within a few hours, but definitely today.

**Comment by sthalik** [comment]
I'm having some link-time issues. Note that some trivial build system fixes were made and sdk-paths was updated with:

```cmake
setq(SDK_EYEWARE_BEAM "BeamSDK-Windows64-1.1.0")
```

Then the error itself:

```console
LINK: command "C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x86\link.exe /nologo tracker-eyeware-beam\CMakeFiles\opentrack-tracker-eyeware-beam.dir\eyeware_beam.cpp.obj tracker-eyeware-beam\CMakeFiles\opentrack-tracker-eyeware-beam.dir\moc_eyeware_beam.cpp.obj tracker-eyeware-beam\CMakeFiles\opentrack-tracker-eyeware-beam.dir\qrc_eyeware_beam.cpp.obj /out:tracker-eyeware-beam\opentrack-tracker-eyeware-beam.dll /implib:tracker-eyeware-beam\opentrack-tracker-eyeware-beam.lib /pdb:tracker-eyeware-beam\opentrack-tracker-eyeware-beam.pdb /dll /version:0.0 -WX -OPT:REF,ICF=10 -LTCG -DEBUG:FULL -cgthreads:1 -DYNAMICBASE -NXCOMPAT -WX -ignore:4020 -ignore:4217 -LIBPATH:F:\dev\opentrack\..\opentrack-depends\BeamSDK-Windows64-1.1.0\API\cpp\lib api\opentrack-api.lib options\opentrack-options.lib compat\opentrack-compat.lib tracker_client.lib F:\dev\qt-5.15-kde\lib\Qt5Widgets.lib F:\dev\qt-5.15-kde\lib\Qt5Gui.lib F:\dev\qt-5.15-kde\lib\Qt5Network.lib F:\dev\qt-5.15-kde\lib\Qt5Core.lib strmiids.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:tracker-eyeware-beam\opentrack-tracker-eyeware-beam.dll.manifest" failed (exit code 1120) with the following output:
   Creating library tracker-eyeware-beam\opentrack-tracker-eyeware-beam.lib and object tracker-eyeware-beam\opentrack-tracker-eyeware-beam.exp
eyeware_beam.cpp.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: bool __thiscall eyeware::TrackerClient::connected(void)const " (__imp_?connected@TrackerClient@eyeware@@QBE_NXZ)
eyeware_beam.cpp.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: struct eyeware::HeadPoseInfo __thiscall eyeware::TrackerClient::get_head_pose_info(void)const " (__imp_?get_head_pose_info@TrackerClient@eyeware@@QBE?AUHeadPoseInfo@2@XZ)
eyeware_beam.cpp.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall eyeware::TrackerClient::~TrackerClient(void)" (__imp_??1TrackerClient@eyeware@@QAE@XZ)
eyeware_beam.cpp.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall eyeware::TrackerClient::TrackerClient(class std::function<void __cdecl(enum eyeware::NetworkError const &)>,int,int,int,char const *)" (__imp_??0TrackerClient@eyeware@@QAE@V?$function@$$A6AXABW4NetworkError@eyeware@@@Z@std@@HHHPBD@Z)
tracker-eyeware-beam\opentrack-tracker-eyeware-beam.dll : fatal error LNK1120: 4 unresolved externals
[21/241] Building CXX object tracker-hatire\CMakeFiles\opentrack-tracker-hatire.dir\ftnoir_tracker_hat_dialog.cpp.obj
ninja: build stopped: subcommand failed.
```

opentrack uses MSVC 1935 for the release build and downgrading the compiler or the CRT version isn't an option.

The library is linking to CRT version 140. Because of this, it's incorrect to depend on `std::function` ABI. As for the way to fix this, I recommend using an idiomatic function pointer with a `void*` context argument.

I don't know what's wrong with the rest of the symbols. Can you help me here?

**Comment by eyedav** [comment]
About the `setq(SDK_EYEWARE_BEAM "BeamSDK-Windows64-1.1.0")` update, should this path in opentrack-depends [here](https://github.com/opentrack/opentrack-depends/tree/master/eyeware-beam-sdk) also be updated then?

About the fact that `std::function` was used, I just created another [PR](https://github.com/opentrack/opentrack/pull/1627) for replacing C++ API calls with C API calls.

About the other linking errors, do they still occur for you when using the C API as in the above PR? Because I just built with it the Eyeware Beam input module successfully using my fork [here](https://github.com/eyedav/opentrack/actions/runs/4470239647).

**Comment by sthalik** [comment]
I haven't switched opentrack's build to 64-bit. Question is whether you can get a 32-bit SDK. If not, I think the target architecture can be switched temporarily for this release while a proper solution is being researched.

**Comment by sthalik** [comment]
@eyedav grab https://ananke.misaki.pl/opentrack/opentrack-test-20230320_01.7z and see if it works.

**Comment by eyedav** [comment]
@sthalik it works, thanks

**Comment by sthalik** [comment]
@eyedav you need to be credited as an author but your git `user.name` doesn't include your real name. Are you ok with me using your real name in release notes and `README.md`? Otherwise how should I refer to your person? According to BSD values, individuals must be credited and not just contracting companies.

**Comment by eyedav** [comment]
@sthalik I am good with my real name: Davide Mameli.

**Comment by sthalik** [comment]
I think you dropped this. *hands commit rights*

**Pull request merged**
