### PR TITLE
Initial Dutch translations

### PR DESCRIPTION
**Pull request by MathijsG**

### CODE REVIEW

**Comment by sthalik** [comment]
Thanks! Today's nightly build has this translation. I also added a global option to disable translating.

https://www.dropbox.com/sh/823dd4wyhixv5a7/AACB1Iqquvia_keD9jUY2qFBa

**Comment by sthalik** [comment]
@MathijsG I added the translation stub for 2.3.1. But it's best if you can generate the source files yourself.

**Comment by MathijsG** [comment]
How can I do this? Or where can I find them? I only see the russian translations, which is quite some work to remove per file. Is there some empty file with only the original english text? Or am I blind :-P

**Comment by sthalik** [comment]
@MathijsG download `opentrack-2.3.1-i18n-stub.zip`

**Comment by sthalik** [comment]
@MathijsG you now have the .ts files in every release inside `source-code/`.

**Pull request merged**
