### PR TITLE
Hamilton documentation and minor fixes

### PR DESCRIPTION
**Pull request by tombrazier**
This PR began with some ideas about fixing the hamilton filter. After some discussion we concluded that there wasn't a great deal that needed fixing but some better documentation would be beneficial. This PR now addresses that along with a slight improvement in the `alpha` calculation logic. Also, whilst I was at it, I converted some tab indents to spaces to match the surrounding code.

# Start of the original PR...

See full discussion with @GO63-samara in #1666.

### Synopsis

As documented (in Russian but easily google translatable) [here](https://sites.google.com/site/diyheadtracking/home/opentrack/opentrack-hamilton-filter), the alpha value calculated for the hamilton filter should have the following curves:

image

It actually has this:

image

(where, in this case, dead zone is 1.0 and max distance is 10.0)

This PR the logic and the new curves are as intended:

image

### CODE REVIEW

**Comment by GO63-samara** [comment]
Not sure about this fix:
`double alpha = (dist - pos_deadzone) / (pos_max + pos_deadzone + EPSILON);`
`double alpha = (dist - pos_deadzone) / (pos_max + EPSILON);`
Previously, with an increase in the dead zone, the smoothing zone also expanded. Now, when increasing the dead zone, the sum of the dead zones and smoothing will be constant == pos_max.
Try what is best. I don't know which is better.

`alpha *= (pos_max - pos_deadzone) / (pos_max + EPSILON);`
This is good. Maybe a little more readable:
`alpha *= 1.0 - pos_deadzone / (pos_max + EPSILON);`
One less variable, maybe a little faster?

**Comment by GO63-samara** [comment]
And further.
I don't quite understand why you insist on including the line
`if (alpha > 0.0)`
Perhaps you want to exclude the `0^0` case? But `0^0=1`, so there's nothing wrong with that. Why extra `if`?

**Comment by tombrazier** [comment]
@GO63-samara I'll look at your comments later. In the meantime, just a quick note to say I think your original last line might have been correct after all.

**Comment by tombrazier** [comment]
> Not sure about this fix:
> `double alpha = (dist - pos_deadzone) / (pos_max + pos_deadzone + EPSILON);`
> `double alpha = (dist - pos_deadzone) / (pos_max + EPSILON);`
> Previously, with an increase in the dead zone, the smoothing zone also expanded. Now, when increasing the dead zone, the sum of the dead zones and smoothing will be constant == pos_max.

My assumption is that the sum of the dead zones and smoothing is where `alpha` becomes equal to 1.0. Or, putting it differently, `alpha == 1.0` when `dist = pos_max + pos_deadzone`. Is that correct? If so, try it out with the two formulea:

```
           1.0 = alpha = (dist - pos_deadzone) / (pos_max + pos_deadzone)
                   1.0 = (dist - pos_deadzone) / (pos_max + pos_deadzone)
pos_max + pos_deadzone = dist - pos_deadzone
                  dist = pos_max + 2 * pos_deadzone
```
vs
```
           1.0 = alpha = (dist - pos_deadzone) / pos_max
                   1.0 = (dist - pos_deadzone) / pos_max
               pos_max = dist - pos_deadzone
                  dist = pos_max + pos_deadzone
```
The second case is the one that matches my assumption.

> Try what is best. I don't know which is better.

I think either will work, but with different configuration. But only one of them matches your graph. And that depends on whether I have understood the graph correctly.

> alpha *= (pos_max - pos_deadzone) / (pos_max + EPSILON);
> This is good. Maybe a little more readable:
> alpha *= 1.0 - pos_deadzone / (pos_max + EPSILON);
> One less variable, maybe a little faster?

They are equivalent. As you say not referencing `pos_max` twice may be faster but I think there is overhead in loading 1.0 into a CPU register so they cost the same.

But I have been thinking: your original code would mean that when you do the linear interpolation there is never a case where the distance moved is `> dist - pos_deadzone` whereas with the new code if `dist > pos_deadzone + pos_max` then the resulting distance moved will be `> dist - pos_deadzone`. Am I right?

> I don't quite understand why you insist on including the line
> if (alpha > 0.0)
> Perhaps you want to exclude the 0^0 case? But 0^0=1, so there's nothing wrong with that. Why extra if?

0^0 == 1 is a problem for when `dist < pos_deadzone`. In that situation you want `alpha` to be 0.0. To be honest, though, 0^0 is a hypothetical situation because the smallest configurable value for `pos_pow` is 0.001.

I could actually just withdraw this PR. I don't think it really makes a huge difference to how the filter works. But it has been very helpful for me to understand the filter.

**Comment by tombrazier** [comment]
Oh, I have worked out something that was confusing me: the New Input - Dead Zone line is not a horizontal line. The larger the value of New Input, the smaller Dead Zone should appear on the Y axis of this graph:

image

It really looks like this:
Screenshot_2023-06-04_15-13-38

**Comment by GO63-samara** [comment]
`double alpha = (dist - pos_deadzone) / (pos_max + EPSILON);
`
It is not clear what will happen to alpha if `pos_max < pos_deadzone`.
I think there will be a problem.

But here there is no such problem, even if it does not fully correspond to the graph:
`double alpha = (dist - pos_deadzone) / (pos_max + pos_deadzone + EPSILON);
`

I agree with the rest.

**Comment by DaWelter** [comment]
> `alpha *= (pos_max - pos_deadzone) / (pos_max + EPSILON);`
> This is good. Maybe a little more readable:

Are you sure. I can understand not wanting the previous version of this line. Now it's scaling the gain independent of the input based on how much `pos_max` is larger than `pos_deadzone`. Seems rather arbitrary. Maybe this line could be deleted entirely instead.

**Comment by DaWelter** [comment]
I think of `pos_max` as the end of the transition zone where `alpha=1`. Therefore `pos_max` must be larger than `pos_deadzone`. Correct me if I'm wrong though.

**Comment by GO63-samara** [comment]
`alpha` should not tend to `1.0`. This has already been discussed here: 
https://github.com/opentrack/opentrack/pull/1666#issuecomment-1574372634

**Comment by tombrazier** [comment]
> It is not clear what will happen to alpha if pos_max < pos_deadzone.
> I think there will be a problem.

Here is a graph with `pos_max = 10.0` and `pos_deadzone = 20.0`:

Screenshot_2023-06-04_17-52-11

The existing behaviour is:

From `dist == 0.0` to `dist == pos_deadzone`: no movement.
From `dist >= pos_deadzone` to `dist == pos_max + 2 * pos_deadzone`: smoothing scales according to power curve.
From `dist >= pos_max + 2 * pos_deadzone`: minimum smoothing is applied.

My proposed behaviour is:

From `dist == 0.0` to `dist == pos_deadzone`: no movement.
From `dist >= pos_deadzone` to `dist == pos_max + pos_deadzone`: smoothing scales according to power curve.
From `dist >= pos_max + pos_deadzone`: minimum smoothing is applied.

However if I made this change it would mean existing users would have to reduce their `pos_max` values by `pos_deadzone`. I am happy just revert my change and stick with the existing behaviour.

I think I will add a comment to explain the last line.

Also, @GO63-samara what do you think about me putting some instructions into the configuration dialog? I suspect more people will use hamilton if they understand what the parameters do.

**Comment by tombrazier** [comment]
> Seems rather arbitrary. Maybe this line could be deleted entirely instead.

@DaWelter The way @GO63-samara explained this line which made sense to me is imagine your head is inside a barrel. When you move your head to the edge of the barrel it begins to push the barrel to a new position. But in the new position your head is still touching the edge of the barrel - or maybe it is a little beyond the edge of the barrel and still pulling it into position. This imposes a limit of the value of `alpha`. It must not be that the new distance from the center of the barrel to your head is now less than the radius of the barrel. So when the `position += alpha * distance` linear interpolation happens, `alpha` must be small enough to ensure that the distance moved is not more than `dist - pos_deadzone`. The existing formula of `(dist - pos_deadzone) / dist` gives this guarantee.

> P.S. then there will also be no problems with alpha becoming negative.

I thought that too. Until I realised that the only way alpha could be multiplied by a negative number is if it is already 0.0.

> Finally, judging from double alpha = (dist - pos_deadzone) / (pos_max + EPSILON);, (which is fine imo), the pos_max behaves more like the size of the transition zone, starting after pos_deadzone, because alpha = 1 at dist == pos_deadzone + pos_max.

That is my understanding too.

**Comment by GO63-samara** [comment]
> Also, @GO63-samara what do you think about me putting some instructions into the configuration dialog? I suspect more people will use hamilton if they understand what the parameters do.

Of course add some instructions.
If you are good with English, you can add the translation to https://github.com/opentrack/opentrack/wiki.
My English is not good enough.

**Comment by tombrazier** [comment]
> If you are good with English, you can add the translation to https://github.com/opentrack/opentrack/wiki.

Do you know how to add a page to the wiki? It looks like you need write access. The google translation of your explanatory page is very good. We could just use that.

**Comment by tombrazier** [comment]
@GO63-samara I have done as discussed and changed the title post for this PR.

The new config dialog looks like this:
hamilton

In addition to adding comments, I re-ordered the settings because I think it flows better to think in terms of dead zone &rarr; max distance &rarr; smoothing power. I'll change these back if you don't like it.

**Comment by GO63-samara** [comment]
This is good

**Comment by DaWelter** [comment]
> alpha should not tend to 1.0. This has already been discussed here
@GO63-samara It should be fine for alpha<1. Minus some wiggle room for rounding errors maybe. When alpha =1 the measured position is outputted. Correct me if I missed something.

> The existing formula of `(dist - pos_deadzone) / dist` gives this guarantee.
Hm ... yes ... I confused it earlier with something else. Now I see you reverted to this formula, and imo it's also good.

**Comment by sthalik** [comment]
> @sthalik I don't have anything more I think needs doing on this and @GO63-samara is happy with it.

This time you guys have to review and merge it on your own. I can't concentrate on anything for the time being, sorry.

**Comment by tombrazier** [comment]
> This time you guys have to review and merge it on your own. I can't concentrate on anything for the time being, sorry.

Sorry to hear that @sthalik. Does anyone else have write access to the repository?

**Comment by DaWelter** [comment]
I can. As there are no more complaints ...

**Comment by tombrazier** [comment]
Thank you. I have a few more contributions and then I'm done. @DaWelter are you happy if I continue making submissions? My remaining changes are:
- Much faster settling time for EWMA.
- CPU usage improvements for my chroma key changes.
- Efficient wait in the simconnect thread - although I have a question about that because sthalik removed the original 100ms wait in commit c26423c amongst a bunch of other changes. Those changes fixed P3D according to #804 but I don't have P3D to test on. But without the efficient wait that thread spins at 100% CPU.
- My NM filter with the speed based deadzone is maturing. It now uses @GO63-samara's quaternion and spherical deadzone logic. And I am planning to add a EWMA inspired automatic calibration option.

**Comment by sthalik** [comment]
> But without the efficient wait that thread spins at 100% CPU.

The thread runs at 250 Hz. If a filter or proto can't run that fast, it's a bug.

Also look for stdout (need opening the app through windows console) [warning messages](https://github.com/opentrack/opentrack/blob/master/logic/pipeline.cpp#L596-L601) about the main loop being unable to keep up.

**Comment by tombrazier** [comment]
> The thread runs at 250 Hz. If a filter or proto can't run that fast, it's a bug.

The `pipeline::run()` thread runs at 250Hz. I am referring to the `simconnect::run()` thread, which watches for `Frame` notifications from SimConnect. This thread sits in a tight loop calling `WaitForSingleObject()` and passing a timeout of 0ms. Change the timeout to 1ms and the CPU usage drops dramatically.

**Comment by sthalik** [comment]
The code expects that `simconnect_calldispatch` doesn't return immediately, and succeeds each time while tracking.

Try looking at the timings, maybe there's a way to avoid context switches and jitter. But it definitely needs a fix one way or another.

**Comment by tombrazier** [comment]
> Try looking at the timings, maybe there's a way to avoid context switches and jitter. But it definitely needs a fix one way or another.

So is the 0ms to avoid context switches? (i.e. by preventing the thread from going into an efficient wait state.)

`simconnect_calldispatch` does return immediately with FSX. I don't know about other simulators.

I have found (with FSX) that `simconnect_set6DOF` doesn't seem to mind which thread it is called from. So it can be called directly from `simconnect::pose`. With `simconnect::pose` being called 250 times a second, this should minimise jitter.

**Comment by sthalik** [comment]
> So is the 0ms to avoid context switches? (i.e. by preventing the thread from going into an efficient wait state.)

If `calldispatch` didn't improperly return without blocking, that would be one context switch too many.

> I have found (with FSX) that simconnect_set6DOF doesn't seem to mind which thread it is called from.

Add a commit fixing it in preferred way for me to cherry-pick.

Possibly many users had the same problem and nobody said anything for years. Sad. It's good that you mentioned it, anyway.

**Comment by tombrazier** [comment]
https://github.com/tombrazier/opentrack/tree/efficientwait is the simplest fix and it makes a big difference. But it would be good to have some users with P3D and MSFS test it.

**Comment by GO63-samara** [comment]
@tombrazier 
One more note.
When I created the Hamilton filter, I did not yet know about the existence of the `QQuaternion` class in Qt.
If we rewrite the `hamilton-tools` files using the `QQuaternion` class, we get a shorthand for the Opentrack code.
You can also take into account that quaternions are used, for example, both in `neuralnet` and in `kinect-face` trackers.
This means that there are ways to optimize the code for other trackers too.

**Comment by GO63-samara** [comment]
I also want to add that the `QQuaternion` class is already used in `pose-widget`.

**Comment by tombrazier** [comment]
Thanks, I think this is an important observation. I will change all my code to use QQuaternion and, if you're happy with it, will also mod the Hamilton filter so there is consistency across all the modules.

**Pull request merged**
