### PR TITLE
RFC: proto-wine UI changes second attempt

### PR DESCRIPTION
**Pull request by Priton-CE**
new branch
old [PR](https://github.com/opentrack/opentrack/pull/1619)

This only contains the changes done to the UI of the proto-wine module.

### CODE REVIEW

**Comment by sthalik** [comment]
Merged, thanks. I have trivial changes but there's no point in holding up this PR.

**Comment by sthalik** [comment]
@ljgdasfhk feel like giving this a spin?

**Comment by ljgdasfhk** [comment]
> @ljgdasfhk feel like giving this a spin?

I do not mind.
But I would like to suggest the following:
1) make it possible to compile without ONNX (I don't have a video card)
2) sorry for the offtopic, this is what is really needed in battle: hotkeys for the selected axis values! (interface should be like curve setting)

**Comment by sthalik** [comment]
> make it possible to compile without ONNX (I don't have a video card)

The only thing that requires onnxruntime is tracker/nn. It also doesn't use the CPU. It runs the network on one or more cores.

Are there any issues at this time?

**Comment by ljgdasfhk** [comment]
> Are there any issues at this time?

i use point-tracker
i think everything works great

**Comment by sthalik** [comment]
I fixed onnxruntime on 32-bit Linux and issues when starting tracking with only one camera present (more serious than it sounds).

**Pull request merged**
